version: '2'
services:
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - $PWD/data/mongo:/data/db
  backend:
    image: besababa/backend
    restart: always
    depends_on:
      - mongodb
    command: ["bash", "-c", "sleep 10 && npm start"]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/eventz
  frontend:
    image: besababa/frontend
    ports:
      - 127.0.0.1:3010:80
  nginx:
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf

