version: '2'
services:
  frontend:
    image: besababa/frontend
    ports:
      - 127.0.0.1:3010:80
  nginx:
    image: nginx
    depends_on:
      - server
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
  server:
    image: besababa/server
    ports:
    - 127.0.0.1:8080:80
    links:
    - database
    volumes:
      - $PWD/laravel/oauth-private.key:/var/www/storage/oauth-private.key:rw
      - $PWD/laravel/oauth-public.key:/var/www/storage/oauth-public.key:rw
    environment:
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_PORT=3306
    - DB_HOST=database
    - DB_DATABASE=besababa
    - APP_DEBUG=true
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}    
  database:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=besababa
    ports:
    - "127.0.0.1:3306:3306"
    volumes:
      - /root/mysql:/var/lib/mysql
  adminer:
    image: adminer
    links:
      - database
